// Generated by CoffeeScript 1.6.2
/*
	Async.js does not seem to work as expected in some
	cases. Writing some quick helpers here
*/


(function() {
  exports.parallel = function(obj, appClbk) {
    var a, add, clbk, ctr, fn, key, len, results, _i, _len, _results, _results1;

    ctr = 0;
    clbk = function(length, results, key, add, err, result) {
      if (err != null) {
        appClbk(err, null);
      } else if (result != null) {
        if (key != null) {
          add(key, result);
        } else {
          add(result);
        }
      }
      if (ctr++ === length - 1) {
        return appClbk(null, results);
      }
    };
    if (_.isObject(obj)) {
      len = Object.keys(obj).length;
      results = {};
      add = function(k, v) {
        return results[k] = v;
      };
      _results = [];
      for (key in obj) {
        fn = obj[key];
        _results.push(fn(clbk.bind(this, len, results, key, add)));
      }
      return _results;
    } else if (_.isArray(obj)) {
      results = [];
      add = function(o) {
        return results.push(o);
      };
      _results1 = [];
      for (_i = 0, _len = obj.length; _i < _len; _i++) {
        a = obj[_i];
        _results1.push(fn(clbk.bind(this, obj.len, results, null, add)));
      }
      return _results1;
    } else {
      return console.error("Unsupported async arg.");
    }
  };

}).call(this);
