// Generated by CoffeeScript 1.4.0

/*
  Class: Getter

  Small module that either requires a file or reads
*/


(function() {
  var Getter, fs;

  fs = require('fs');

  Getter = (function() {

    function Getter(_p) {
      this._p = _p;
    }

    Getter.prototype.load = function(clbk) {
      var _this = this;
      return fs.stat(this._p, function(err, stats) {
        var file, files, _i, _len;
        if (err != null) {
          return clbk(err);
        } else {
          if (stats.isFile()) {
            return _this._elems = require(_this._p);
          } else {
            _this._elems = {};
            files = fs.readdirSync(_this._p);
            for (_i = 0, _len = files.length; _i < _len; _i++) {
              file = files[_i];
              _this._elems[file] = require("" + __dirname + "/file");
            }
            return clbk(null);
          }
        }
      });
    };

    Getter.prototype.get = function() {
      return this._elems;
    };

    Getter.prototype.__defineGetter__('path', function() {
      return this._p;
    });

    return Getter;

  })();

  module.exports = Getter;

}).call(this);
