// Generated by CoffeeScript 1.4.0

/*
  Helper: Middleware

  Transforms middleware representation from
    {
      "middleware1": 'all'
      "middleware2": {only: "tag1"}
    }

    into an ordered array keyed by the name of each route in the file

    {
      "tag1": ["middleware1", "middleware2"]
      "default": ["middleware1"]
    }

    Middleware formatting options are:


    {
      HookName: "String"
    }

    Where "String" is either
      1. "all"
      2. a comma delimited list of tag names "tag1, tag2, tag3"

    authenticate: "a
*/


(function() {

  exports.transform = function(m) {
    var arr, c, keyed, n, str, strs, t, _i, _len;
    keyed = {};
    for (n in m) {
      c = m[n];
      strs = _.map(c.split(','), function(el) {
        return el.replace(/\s/g, "");
      });
      if (strs[0] === 'all') {
        for (t in keyed) {
          m = keyed[t];
          m.push(n);
        }
        if (!(keyed['default'] != null)) {
          keyed['default'] = [n];
        }
      } else {
        for (_i = 0, _len = strs.length; _i < _len; _i++) {
          str = strs[_i];
          arr = keyed[str] || (keyed["default"] || []);
          arr.push(n);
          keyed[str] = arr;
        }
      }
    }
    return keyed;
  };

}).call(this);
