// Generated by CoffeeScript 1.6.2
(function() {
  var CriscoAux;

  CriscoAux = (function() {
    /*
    
      CLASS METHODS
    */

    /*
      Private Class Var Container
    */
    CriscoAux.__vars = {};

    /*
      Static Class Method: Config
    
      Deals with storing the application level
      configurations.
    
      @param - appConfigs
    
      @param - domainConfigs
    
      @param - database
    */


    CriscoAux.config = function(appConfigs, domainConfigs, database) {
      this.__vars.configs = this.__vars.configs || {};
      this.__vars.configs.app = appConfigs;
      this.__vars.configs.domain = domainConfigs;
      return this.__vars.database = database;
    };

    /*
      Static Class Method: Init
    
      Deals with initializing a new instance of
      CriscoModel.  This understands how to initialize
      off a "req" object from express.
    
      @param - domain - A string representing the
               domain to initalize a new string
    
      @param -
    */


    CriscoAux.init = function(crisco, domain, req, res) {
      /*
        Eventually we'll also include logic to initialize
        and cache any shared resources between CriscoModel.
      */

      var cm, routeInfo;

      routeInfo = {
        req: req,
        res: res
      };
      cm = new this(crisco, domain, this.__vars.database, routeInfo);
      return cm;
    };

    /*
      
      INSTANCE METHODS
    */


    /*
      Method: constructor
    
      @param - domain <String>, The current
      @param - database <Object>, and instance
               of the dojo database object.
      @param - routeInfo - an object containing
               information about this specific
               request
               Includes:
                    routeInfo =
                      route: {
                        Express Object from req.route: see 
                        http://expressjs.com/api.html#req.route for more info
                      } 
                      method: "GET|POST|PUT|DELETE"
                      query:  {queryString: Parameter}
                      body:   {body: Parameter}
               Query and/or body may not be defined
               depending on the HTTP Method used
                
                Example express req.route object:
                { 
                  path: '/user/:id?',
                  method: 'get',
                  callbacks: [ [Function] ],
                  keys: [ { name: 'id', optional: true } ],
                  regexp: /^\/user(?:\/([^\/]+?))?\/?$/i,
                  params: [ id: '12' ] 
                }
    */


    function CriscoAux(crisco, domain, database, routeInfo) {
      this.__crisco = crisco;
      this.__domain = domain;
      this.__database = database;
      this.__routeInfo = routeInfo;
      this.__cache = {};
    }

    /*
      Method: log
      
      A configured logger instance for each domain.
      For now defer to default console.log
    */


    CriscoAux.prototype.log = function() {
      return console.log;
    };

    /*
      Method: error
    
      A configured error instance for each domain.
      For now defer to default console.error
    */


    CriscoAux.prototype.error = function() {
      return console.error;
    };

    /*
      Getters
    */


    /*
      req - An untouched Express.js req object.
    */


    CriscoAux.prototype.__defineGetter__("req", function() {
      return this.__routeInfo.req;
    });

    /*
      res - An untouched Express.js res object.
    */


    CriscoAux.prototype.__defineGetter__("res", function() {
      return this.__routeInfo.res;
    });

    CriscoAux.prototype.__defineGetter__("body", function() {
      return this.__routeInfo.req.body;
    });

    CriscoAux.prototype.__defineGetter__("crisco", function() {
      return this.__crisco;
    });

    CriscoAux.prototype.__defineGetter__("me", function() {
      if (this.__routeInfo.req.__crisco == null) {
        return null;
      } else {
        return this.__routeInfo.req.__crisco.me;
      }
    });

    return CriscoAux;

  })();

  module.exports = CriscoAux;

}).call(this);
