// Generated by CoffeeScript 1.6.3
(function() {
  var Info;

  Info = (function() {
    function Info() {
      this.__info = {};
    }

    Info.prototype.set = function(property, value) {
      return this.__info[property] = value;
    };

    Info.prototype.get = function(property) {
      return this.__info[property];
    };

    return Info;

  })();

  module.exports = Info;

}).call(this);
