// Generated by CoffeeScript 1.4.0

/*
  A collection of the first N
  steps of Crisco initialization.
*/


(function() {
  var CriscoModels;

  CriscoModels = require("" + __dirname + "/../../models/criscomodelfactory");

  /*
    Step 1:
  
    -Create a namespaced __crisco variable
    container the express req object.
  
    -Call user registered deserializer
    if it exists.
  */


  exports.one = function(req, res, next) {
    var h, m;
    req.__crisco = {};
    h = function(me) {
      if (me != null) {
        req.__crisco.me = me;
      }
      return next();
    };
    m = Crisco.getMiddleware("deserialize");
    if (m != null) {
      return m.call(m, req, res, h);
    } else {
      return next();
    }
  };

  /*
    Step 2:
  
    -Create CriscoModel and Aux
    instances
  */


  exports.two = function(domain) {
    var _this = this;
    return function(req, res, next) {
      var cm;
      cm = CriscoModels.get('domain');
      return req.__crisco.model = cm.init(req);
    };
  };

}).call(this);
