// Generated by CoffeeScript 1.4.0

/*
  A collection of the first N
  steps of Crisco initialization.
*/


(function() {
  var CriscoModels, CriscoResourceInit, Middleware;

  CriscoModels = require("" + __dirname + "/../../models/criscomodelfactory");

  /*
   Let's just define the ordered middleware here. Bind each
   anonymous function to this context so it get's access
  */


  Middleware = {
    /*
        Step 1:
    
        -Create a namespaced __crisco variable
        container the express req object.
    
        -Call user registered deserializer
        if it exists.
    */

    '1': function(req, res, next) {
      var h, m;
      req.__crisco = {};
      h = function(me) {
        if (me != null) {
          req.__crisco.me = me;
        }
        return next();
      };
      console.log;
      m = Crisco.getMiddleware("deserialize");
      if (m != null) {
        return m.call(m, req, res, h);
      } else {
        return next();
      }
    },
    /*
        Step 2:
    
        -Create CriscoModel and Aux
        instances
    
      # TODO(chris): Might need to curry with
        domainConfig if CriscoModel needs
        domain configurable options to bootstrap
        itself.
    */

    '2': function(domain) {
      var _this = this;
      return function(req, res, next) {
        var aux, cm;
        console.log("Initializing Crisco Models Primitives");
        cm = _this.__CriscoModels.get(domain);
        req.__crisco.model = cm.init(req);
        aux = {
          req: req,
          res: res,
          log: console.log,
          error: console.error
        };
        req.__crisco.aux = aux;
        return next();
      };
    }
  };

  CriscoResourceInit = (function() {

    function CriscoResourceInit(database, appConfig) {
      this.__db = database;
      this.__CriscoModels = new CriscoModels(appConfig, this.__db);
    }

    CriscoResourceInit.prototype.init = function() {
      var route, step, _results;
      _results = [];
      for (step in Middleware) {
        route = Middleware[step];
        _results.push(Middleware[step] = route.bind(this));
      }
      return _results;
    };

    CriscoResourceInit.prototype.getExpressMiddleware = function(domain) {
      return [Middleware['1'], Middleware['2'](domain)];
    };

    return CriscoResourceInit;

  })();

  module.exports = CriscoResourceInit;

}).call(this);
