// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(CriscoModels, Aux, next) {
    var node, nodeManager, target, targets, _i, _len,
      _this = this;

    console.log("Running Permission Middleware");
    targets = CriscoModels.targets();
    nodeManager = CriscoModels.database.nodeManager;
    for (_i = 0, _len = targets.length; _i < _len; _i++) {
      target = targets[_i];
      node = nodeManager.find(target);
      if (node.isRoot) {
        return CriscoModels.populate(function(err, models) {
          return next();
        });
      }
    }
    console.error("Could not find a root for permissions please check route " + Aux.req.url);
    return Aux.res.json(401, {
      message: "Not authorized"
    });
  };

}).call(this);
