// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(CriscoModels, Aux, next) {
    var node, nodeManager, target, targets, _i, _len, _results,
      _this = this;
    console.log("Running Permission Middleware");
    targets = CriscoModels.targets();
    nodeManager = CriscoModels.database.nodeManager;
    _results = [];
    for (_i = 0, _len = targets.length; _i < _len; _i++) {
      target = targets[_i];
      node = nodeManager.find(target);
      if (node.isRoot) {
        _results.push(CriscoModels.populate(function(err, models) {
          return next();
        }));
      } else {
        console.error("Could not find a root for permissions please check route " + Aux.req.url);
        _results.push(next());
      }
    }
    return _results;
  };

}).call(this);
