// Generated by CoffeeScript 1.6.2
/*
  Class: CriscoActionInit

  A collection of middleware
  and it's initializer that
  initialize Crisco Primitives
*/


(function() {
  var CriscoActionInit;

  CriscoActionInit = (function() {
    function CriscoActionInit() {}

    CriscoActionInit.prototype.init = function() {};

    CriscoActionInit.prototype.getExpressMiddleware = function(domain) {
      return [];
    };

    return CriscoActionInit;

  })();

  module.exports = CriscoActionInit;

}).call(this);
