// Generated by CoffeeScript 1.6.2
(function() {
  var CriscoResourceInit, ResourceInitializer;

  CriscoResourceInit = require("" + __dirname + "/../middleware.resource/init");

  /*
    Class: ResourceInitializer
  
    Initializes a set of express compliant middleware that
    takes the raw request object and creates the Crisco
    route primitives CriscoModels and Aux
  
    @param - database - An instance of database
    @param - primitiveFactory - An instance of primitiveFactory
             that can initialize application primitives such
             as CriscoModel, CriscoAction, and Aux
  */


  ResourceInitializer = (function() {
    function ResourceInitializer(database, primitiveFactory) {
      this.__db = database;
      this.__resourceInit = new CriscoResourceInit(this.__db, primitiveFactory);
      this.__resourceInit.init();
    }

    /*
      Method: get
    
      Returns an array of express middleware
      compliant functions that create
      our crisco resource primitives
    */


    ResourceInitializer.prototype.get = function(domain) {
      return this.__resourceInit.getExpressMiddleware(domain);
    };

    return ResourceInitializer;

  })();

  module.exports = ResourceInitializer;

}).call(this);
