// Generated by CoffeeScript 1.6.2
(function() {
  var DefaultAction,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DefaultAction = (function() {
    /*
        Where a route object is defined as:
        {
          tag: "routeTag"
          route: "/route"
          method: "GET|PUT|POST|DEL"
          handler: RouteFn
        }
    */
    function DefaultAction(r) {
      this.handler = __bind(this.handler, this);      this.__r = r;
    }

    DefaultAction.prototype.handler = function(req, res, next) {
      var Aux, CriscoAction,
        _this = this;

      CriscoAction = req.__crisco.action;
      Aux = req.__crisco.aux;
      return this.__r.handler(CriscoAction, Aux, function(runDefault) {
        if (runDefault == null) {
          runDefault = false;
        }
        return console.log("There is no default action implementation. Skipping...");
      });
    };

    DefaultAction.prototype.__defineGetter__('route', function() {
      return this.__r.route;
    });

    return DefaultAction;

  })();

  module.exports = DefaultAction;

}).call(this);
