// Generated by CoffeeScript 1.4.0

/*
  Class: ActionCollector

  Collects Action level configurations and carries out
  the appropriate operations to add them to an initialized
  express instance.
*/


(function() {
  var ActionCollector, ActionDomain;

  ActionDomain = require("" + __dirname + "/../domains/action");

  ActionCollector = (function() {

    function ActionCollector(express) {
      this._e = express;
      this._actions = {};
    }

    ActionCollector.prototype.add = function(name, config) {
      var ad;
      ad = new ActionDomain(this._e, config);
      ad.enrich();
      return this._actions[name] = ad;
    };

    ActionCollector.prototype.get = function(name) {
      if (name != null) {
        return this._actions[name];
      } else {
        return this._actions;
      }
    };

    return ActionCollector;

  })();

  module.exports = ActionCollector;

}).call(this);
