// Generated by CoffeeScript 1.4.0

/*
  Class: ActionCollector

  Collects Action level configurations and carries out
  the appropriate operations to add them to an initialized
  express instance.
*/


(function() {
  var ResourceCollector, ResourceDomain;

  ResourceDomain = require("" + __dirname + "/../domains/action");

  ResourceCollector = (function() {

    function ResourceCollector(express) {
      this._e = express;
      this._resources = {};
    }

    ResourceCollector.prototype.add = function() {};

    ResourceCollector.prototype.get = function(name) {
      if (name != null) {
        return this._resources[name];
      } else {
        return this._resources;
      }
    };

    return ResourceCollector;

  })();

  module.exports = ResourceCollector;

}).call(this);
