// Generated by CoffeeScript 1.4.0

/*
  Class: ResourceCollector

  Collects Resource level configurations and carries out
  the appropriate operations to add them to an initialized
  express instance.
*/


(function() {
  var ResourceCollector, ResourceDomain;

  ResourceDomain = require("" + __dirname + "/../domains/resource");

  ResourceCollector = (function() {

    function ResourceCollector(express, conditioner) {
      this.__e = express;
      this.__cond = conditioner;
      this.__resources = {};
    }

    /*
        Method: add
        
        Adds a resourceDomain to the ResourceDomain collection.
        
        @param "string" that's the name of this particular domain
        @param "object" describing the state of the resource domain
    */


    ResourceCollector.prototype.add = function(name, config) {
      var rd;
      rd = new ResourceDomain(this.__e, config, this.__cond);
      rd.enrich();
      return this.__resources[name] = rd;
    };

    ResourceCollector.prototype.get = function(name) {
      if (name != null) {
        return this.__resources[name];
      } else {
        return this.__resources;
      }
    };

    return ResourceCollector;

  })();

  module.exports = ResourceCollector;

}).call(this);
