// Generated by CoffeeScript 1.6.2
/*
  Class: ResourceCollector

  Collects Resource level configurations and carries out
  the appropriate operations to add them to an initialized
  express instance.
*/


(function() {
  var ResourceCollector, ResourceDomain;

  ResourceDomain = require("" + __dirname + "/../domains/resource");

  ResourceCollector = (function() {
    function ResourceCollector(crisco, express, resourceInitializer) {
      this.__c = crisco;
      this.__e = express;
      this.__r = resourceInitializer;
      this.__resources = {};
    }

    /*
      Method: add
      
      Adds a resourceDomain to the ResourceDomain collection. This
      also initializes the server instance with this resource
      domain
      
      @param "string" that's the name of this particular domain
      @param "object" describing the state of the resource domain
    */


    ResourceCollector.prototype.add = function(name, config) {
      var rd;

      rd = new ResourceDomain(this.__e, config, this.__r);
      rd.enrich();
      return this.__resources[name] = rd;
    };

    ResourceCollector.prototype.get = function(name) {
      if (name != null) {
        return this.__resources[name];
      } else {
        return this.__resources;
      }
    };

    return ResourceCollector;

  })();

  module.exports = ResourceCollector;

}).call(this);
