// Generated by CoffeeScript 1.6.2
/*
  Class: Primitive Factory

  Handles initializing new Crisco Primitives:
    -CriscoModel
    -CriscoAction
    -Aux
*/


(function() {
  var PrimitiveFactory;

  PrimitiveFactory = (function() {
    /*
      Method: constructor
    
      @param - appConfig - Application level configurations
               defined on Crisco.
      @param - domainConfig - An object containing all the
               serialized action and resource domain
               configurations
      @param - database - instance of database
    */
    function PrimitiveFactory(appConfig, domainConfig, database) {
      this.__configs = {
        app: appConfig,
        domain: domainConfig
      };
      this.__database = database;
      this.__primitives = {};
    }

    PrimitiveFactory.prototype.registerPrimitive = function(name, P) {
      P.config(this.__configs.app, this.__configs.domain, this.__database);
      return this.__primitives[name] = P;
    };

    PrimitiveFactory.prototype.getPrimitive = function(name, domain, req, res) {
      var P;

      P = this.__primitives[name];
      if (P == null) {
        return null;
      }
      return P.init(domain, req, res);
    };

    return PrimitiveFactory;

  })();

  module.exports = PrimitiveFactory;

}).call(this);
