// Generated by CoffeeScript 1.6.2
(function() {
  var CriscoResourceHandler, CriscoResourceRoute;

  CriscoResourceHandler = require("" + __dirname + "/../router/");

  /*
    Class: CriscoResourceRoute
  
    Responsible for taking a resource route configuration
    and exporting an appropriately configured CriscoResourceHandler
    into the Crisco route application space.
  */


  CriscoResourceRoute = (function() {
    /*
      Method: constructor
    
      Takes a resource route config which looks like
        {
          tag: "Tag",
          route: "Route",
        }
    */
    function CriscoResourceRoute(config) {
      this._c = config;
    }

    CriscoResourceRoute.prototype.build = function() {
      return console.log("Building action route...");
    };

    CriscoResourceRoute.prototype.enrich = function(express, clbk) {
      return console.log("Enriching crisco resource route");
    };

    return CriscoResourceRoute;

  })();

  module.exports = CriscoResourceRoute;

}).call(this);
