// Generated by CoffeeScript 1.6.2
/*
  Class: ActionDomain

  Responsible for configuring an express
  server instance with a single action
  domain.
*/


(function() {
  var ActionDomain;

  ActionDomain = (function() {
    /*
      Method: constructor
    
      @param express -
    */
    function ActionDomain(express, config, database) {
      this.__e = express;
      this.__c = config;
      this.__d = database;
    }

    ActionDomain.prototype.enrich = function() {
      return console.log("Enriching an action");
    };

    return ActionDomain;

  })();

  module.exports = ActionDomain;

}).call(this);
