// Generated by CoffeeScript 1.4.0

/*
  Class: ActionDomain

  Responsible for configuring an express
  server instance with a single action
  domain.
*/


(function() {
  var ActionDomain;

  ActionDomain = (function() {

    function ActionDomain(express, config) {
      this._e = express;
      this._c = config;
    }

    ActionDomain.prototype.enrich = function() {
      return console.log("Enriching an action");
    };

    return ActionDomain;

  })();

  module.exports = ActionDomain;

}).call(this);
