// Generated by CoffeeScript 1.6.2
(function() {
  var ActionConditioner, CriscoResourceInit;

  CriscoResourceInit = require("" + __dirname + "/../../middleware/default/crisco_action_init");

  ActionConditioner = (function() {
    function ActionConditioner(database) {
      this.__db = database;
      this.__resourceInit = new CriscoResourceInit(this.__db);
    }

    ActionConditioner.prototype.get = function(domain) {
      return this.__resourceInit;
      return [];
    };

    return ActionConditioner;

  })();

  module.exports = ActionConditioner;

}).call(this);
