// Generated by CoffeeScript 1.4.0
(function() {
  var ActionConditioner;

  ActionConditioner = (function() {

    function ActionConditioner(database) {
      this.__db = database;
    }

    ActionConditioner.prototype.get = function(domain) {
      return [];
    };

    return ActionConditioner;

  })();

  module.exports = ActionConditioner;

}).call(this);
