// Generated by CoffeeScript 1.6.2
(function() {
  var CriscoModels, CriscoResourceInit, ResourceConditioner;

  CriscoResourceInit = require("" + __dirname + "/../../middleware/default/crisco_resource_init");

  CriscoModels = require("" + __dirname + "/../../models/criscomodelfactory");

  /*
    Class: ResourceConditioner
  
    Initializes a set of express compliant middleware that
    takes the raw request object and creates the Crisco
    route primitives CriscoModels and Aux
  */


  ResourceConditioner = (function() {
    function ResourceConditioner(database) {
      this.__db = database;
      this.__resourceInit = new CriscoResourceInit(this.__db, Crisco.appConfig);
      this.__resourceInit.init();
    }

    /*
      Method: get
    
      Returns an array of express middleware
      compliant functions that create
      our crisco resource primitives
    */


    ResourceConditioner.prototype.get = function(domain) {
      return this.__resourceInit.getExpressMiddleware(domain);
    };

    return ResourceConditioner;

  })();

  module.exports = ResourceConditioner;

}).call(this);
