// Generated by CoffeeScript 1.4.0

/*
  Class: Aux

  Aux takes a resource configuration and exposes
*/


(function() {
  var Aux;

  Aux = (function() {

    function Aux() {}

    /*
        Method: log
    
        Proxies the log message to the application
        logger.
    */


    Aux.prototype.log = function() {};

    /*
        Method: error
    
        Proxies the error message to the application
        error logger.
    */


    Aux.prototype.error = function() {};

    /*
        Method: set
    
        Used to set variables on this instance, but
        should really only be used to set express
        req and res instances.
    */


    Aux.prototype.set = function(name, v) {
      return this["__" + name] = v;
    };

    Aux.prototype.__defineGetter__('req', function() {
      return this.__req;
    });

    Aux.prototype.__defineGetter__('res', function() {
      return this.__res;
    });

    return Aux;

  })();

  module.exports = Aux;

}).call(this);
