// Generated by CoffeeScript 1.4.0
(function() {
  var Aux, AuxFactory;

  Aux = require("" + __dirname + "/aux");

  /*
    Class: AuxFactory
  
    Responsible for configuring Aux
    instances for  each domain given an application
    config.
  */


  AuxFactory = (function() {

    function AuxFactory(appConfig, domainConfigs) {
      this.__appConfig = appConfig;
      this.__domainConfigs = domainConfigs;
      this.__auxes = {};
    }

    AuxFactory.prototype.get = function(domain) {
      return console.log("Getting aux for domain " + domain);
    };

    return AuxFactory;

  })();

  module.exports = AuxFactory;

}).call(this);
