// Generated by CoffeeScript 1.4.0
(function() {
  var ActionInitializer;

  ActionInitializer = (function() {

    function ActionInitializer(actionGetter) {
      this._actionGetter = actionGetter;
    }

    ActionInitializer.prototype.init = function(clbk) {
      var _this = this;
      return this._actionGetter.load(function(err) {
        return clbk(err);
      });
    };

    /*
        Method: enrich
    
        Takes an express instance and enriches the
        server with the appropriate models.
    */


    ActionInitializer.prototype.enrich = function(express, clbk) {
      var ActionConfigurations;
      return ActionConfigurations = this._actionGetter.get();
    };

    return ActionInitializer;

  })();

  module.exports = ActionInitializer;

}).call(this);
