// Generated by CoffeeScript 1.4.0

/*
  Application Initializers
*/


(function() {
  var ActionCollector, AppInitializer, Express, ResourceCollector, RouteInitializer, SchemaInitializer;

  SchemaInitializer = require("" + __dirname + "/schema");

  RouteInitializer = require("" + __dirname + "/route");

  /*
    Action and Resource Collectors
  */


  ActionCollector = require("" + __dirname + "/../collectors/action");

  ResourceCollector = require("" + __dirname + "/../collectors/resource");

  Express = require("express");

  AppInitializer = (function() {
    /*
        Method: constructor
    */

    function AppInitializer(actionsG, resourcesG, schemasG, pluginsG, dbSettingsG) {
      this._s = schemasG;
      this._r = resourcesG;
      this._p = pluginsG;
      this._a = actionsG;
      this._dbSettings = dbSettingsG;
      this._initializers = {};
      this._e = Express();
    }

    AppInitializer.prototype.init = function(clbk) {
      var actionCollector, resourceCollector,
        _this = this;
      resourceCollector = new ResourceCollector(this._e);
      actionCollector = new ActionCollector(this._e);
      this._initializers.schema = new SchemaInitializer(this._s, this._p, this._dbSettings);
      this._initializers.resource = new RouteInitializer(this._r, resourceCollector);
      this._initializers.action = new RouteInitializer(this._a, actionCollector);
      return this._init(function(err) {
        if (err != null) {
          console.error("Error In Application Initialization");
          return console.error(err.message);
        } else {
          return _this._initializers.resource.enrich();
        }
      });
    };

    AppInitializer.prototype._init = function(clbk) {
      var _this = this;
      return this._initializers.schema.init(function(err) {
        return _this._initializers.resource.init(function(err) {
          return _this._initializers.action.init(function(err) {
            return clbk(null);
          });
        });
      });
    };

    return AppInitializer;

  })();

  module.exports = AppInitializer;

}).call(this);
