// Generated by CoffeeScript 1.4.0
(function() {
  var ActionInitializer, AppInitializer, ResourceInitializer, SchemaInitializer;

  SchemaInitializer = require("" + __dirname + "/schema");

  ResourceInitializer = require("" + __dirname + "/resource");

  ActionInitializer = require("" + __dirname + "/action");

  AppInitializer = (function() {
    /*
        Method: constructor
    */

    function AppInitializer(schemas, resources, plugins, dbSettings, actions) {
      this._s = schemas;
      this._r = resources;
      this._p = plugins;
      this._dbSettings = dbSettings;
      this._initializers = {};
    }

    AppInitializer.prototype.init = function(clbk) {
      var _action, _resource, _schema,
        _this = this;
      this._initializers.schema = _schema = new SchemaInitializer(this._s, this._p, this._dbSettings);
      this._initializers.resource = _resource = new ResourceInitializer(this._r);
      this._initializers.action = _action = new ActionInitializer(this._p);
      return _schema.init(function(err) {
        return _resource.init(function(err) {
          return _action.init(function(err) {});
        });
      });
    };

    return AppInitializer;

  })();

  module.exports = AppInitializer;

}).call(this);
