// Generated by CoffeeScript 1.6.2
(function() {
  var ActionCollector, ActionConditioner, AppInitializer, Express, ResourceCollector, ResourceConditioner, RouteInitializer, SchemaInitializer;

  Express = require("express");

  /*
    Application Initializers
  */


  SchemaInitializer = require("" + __dirname + "/schema");

  RouteInitializer = require("" + __dirname + "/route");

  /*
    Action and Resource Collectors
  */


  ActionCollector = require("" + __dirname + "/../collectors/action");

  ResourceCollector = require("" + __dirname + "/../collectors/resource");

  /*
    Route Conditioners
  */


  ResourceConditioner = require("" + __dirname + "/conditioners/resource");

  ActionConditioner = require("" + __dirname + "/conditioners/action");

  AppInitializer = (function() {
    /*
      Method: constructor
    */
    function AppInitializer(actionsG, resourcesG, schemasG, pluginsG, dbSettingsG) {
      this.__s = schemasG;
      this.__r = resourcesG;
      this.__p = pluginsG;
      this.__a = actionsG;
      this.__dbSettings = dbSettingsG;
      this.__initializers = {};
      this.__e = Express();
    }

    AppInitializer.prototype.init = function(clbk) {
      var _this = this;

      this.__initializers.schema = new SchemaInitializer(this.__s, this.__p, this.__dbSettings);
      return this.__initializers.schema.init(function(err) {
        var actionCollector, actionConditioner, db, resourceCollector, resourceConditioner;

        if (err != null) {
          console.error("Problem initializing the database");
          return console.error(err.message);
        } else {
          db = _this.__initializers.schema.database;
          resourceConditioner = new ResourceConditioner(db);
          actionConditioner = new ActionConditioner(db);
          resourceCollector = new ResourceCollector(_this.__e, resourceConditioner);
          actionCollector = new ActionCollector(_this.__e, resourceConditioner);
          _this.__initializers.resource = new RouteInitializer(_this.__r, resourceCollector);
          _this.__initializers.action = new RouteInitializer(_this.__a, actionCollector);
          return _this.__initializers.resource.init(function(err) {
            if (err != null) {
              return clbk(err);
            } else {
              return _this.__initializers.action.init(function(err) {
                if (err != null) {
                  return clbk(err);
                } else {
                  console.log("Initializing resources...");
                  _this.__initializers.resource.enrich();
                  return clbk(null, _this.__e);
                }
              });
            }
          });
        }
      });
    };

    return AppInitializer;

  })();

  module.exports = AppInitializer;

}).call(this);
