// Generated by CoffeeScript 1.4.0
(function() {
  var ResourceInitializer;

  ResourceInitializer = (function() {

    function ResourceInitializer(resourceGetter) {
      this._resourceGetter = resourceGetter;
    }

    ResourceInitializer.prototype.init = function(clbk) {
      var _this = this;
      return this._resourceGetter.load(function(err) {
        return clbk(err);
      });
    };

    ResourceInitializer.prototype.enrich = function(express, clbk) {
      var ResourceConfigurations, config, _i, _len, _results;
      ResourceConfigurations = this._resourceGetter.get();
      _results = [];
      for (_i = 0, _len = ResourceConfigurations.length; _i < _len; _i++) {
        config = ResourceConfigurations[_i];
        _results.push(console.log("Enriching resources..."));
      }
      return _results;
    };

    return ResourceInitializer;

  })();

  module.exports = ResourceInitializer;

}).call(this);
