// Generated by CoffeeScript 1.4.0
(function() {
  var ResourceInitializer;

  ResourceInitializer = (function() {

    function ResourceInitializer(resourceGetter) {
      this._resourceGetter = resourceGetter;
    }

    ResourceInitializer.prototype.init = function(clbk) {
      this._resourceGetter.init();
      return clbk();
    };

    ResourceInitializer.prototype.enrich = function(express, clbk) {
      var ResourceConfigurations, config, rName, _results;
      ResourceConfigurations = this._resourceGetter.get();
      _results = [];
      for (rName in ResourceConfigurations) {
        config = ResourceConfigurations[rName];
        console.log("Enriching resource...", rName);
        _results.push(console.log(config.serialize()));
      }
      return _results;
    };

    return ResourceInitializer;

  })();

  module.exports = ResourceInitializer;

}).call(this);
