// Generated by CoffeeScript 1.4.0

/*
  Class: AssetInitializer

  Initializes Action
*/


(function() {
  var RouteInitializer;

  RouteInitializer = (function() {
    /*
        Method: constructor
    
        @param - getter - initializes
        @param - collector - a collector that initializes
                 the application with serialized route instances
        @param - conditioner - a request conditioner that knows
                 how to transform the raw request express object
                 into crisco route primitives
    */

    function RouteInitializer(getter, collector) {
      this.__g = getter;
      this.__c = collector;
    }

    RouteInitializer.prototype.init = function(clbk) {
      this.__g.init();
      return clbk();
    };

    RouteInitializer.prototype.enrich = function() {
      var confObj, name, _ref, _results;
      _ref = this.__g.get();
      _results = [];
      for (name in _ref) {
        confObj = _ref[name];
        _results.push(this.__c.add(name, confObj.serialize()));
      }
      return _results;
    };

    return RouteInitializer;

  })();

  module.exports = RouteInitializer;

}).call(this);
