// Generated by CoffeeScript 1.6.3
/*
  Class: SchemaInitializer

  Responsible for initializing the dojodatabase and exposing both the drivers
  and graph to the client.
*/


(function() {
  var Database, SchemaInitializer;

  Database = require("database").Database;

  SchemaInitializer = (function() {
    function SchemaInitializer(__schema, __plugins, __dbSettings) {
      this.__schema = __schema;
      this.__plugins = __plugins;
      this.__dbSettings = __dbSettings;
    }

    SchemaInitializer.prototype.init = function(clbk) {
      var plugin, pluginName, _db, _ref,
        _this = this;
      _db = new Database(this.__schema, this.__dbSettings).init();
      _ref = this.__plugins;
      for (pluginName in _ref) {
        plugin = _ref[pluginName];
        _db.registerPlugin(pluginName, plugin);
      }
      return _db.connect(function(err, criscoDatabase) {
        if (err != null) {
          console.error("Some error handler here");
          return clbk(err);
        } else {
          _this.__criscoDatabase = criscoDatabase;
          return clbk(null);
        }
      });
    };

    SchemaInitializer.prototype.__defineGetter__('database', function() {
      return this.__criscoDatabase;
    });

    return SchemaInitializer;

  })();

  module.exports = SchemaInitializer;

}).call(this);
