// Generated by CoffeeScript 1.6.2
/*
  Class: SchemaInitializer

  Responsible for initializing the dojodatabase and exposing both the drivers
  and graph to the client.
*/


(function() {
  var Database, SchemaInitializer;

  Database = require("database").Database;

  SchemaInitializer = (function() {
    function SchemaInitializer(schemaGetter, pluginGetter, dbSettingsGetter) {
      this._sGetter = schemaGetter;
      this._pGetter = pluginGetter;
      this._dbSettingsGetter = dbSettingsGetter;
    }

    SchemaInitializer.prototype.init = function(clbk) {
      var plugin, pluginName, _db, _plugins,
        _this = this;

      _plugins = this._pGetter.get();
      _db = new Database(this._sGetter.path, this._dbSettingsGetter.path).init();
      for (pluginName in _plugins) {
        plugin = _plugins[pluginName];
        _db.registerPlugin(pluginName, plugin);
      }
      return _db.connect(function(err, criscoDatabase) {
        if (err != null) {
          console.error("Some error handler here");
          return clbk(err);
        } else {
          _this._criscoDatabase = criscoDatabase;
          return clbk(null);
        }
      });
    };

    SchemaInitializer.prototype.__defineGetter__('database', function() {
      return this._criscoDatabase;
    });

    return SchemaInitializer;

  })();

  module.exports = SchemaInitializer;

}).call(this);
