// Generated by CoffeeScript 1.6.2
(function() {
  var ActionInitializer, CriscoActionInit;

  CriscoActionInit = require("" + __dirname + "/../middleware.action/init");

  ActionInitializer = (function() {
    function ActionInitializer(crisco, database, primitiveFactory) {
      this.__c = crisco;
      this.__db = database;
      this.__primitiveFactory = primitiveFactory;
      this.__actionInit = new CriscoActionInit(this.__c, this.__db, primitiveFactory);
      this.__actionInit.init();
    }

    /*
      Method: get
    
      Returns an array of express compliant middleware that
      initializes Crisco primitives. For now Actions
      aren't separated into domains like resources...
    */


    ActionInitializer.prototype.get = function(domain, routeInfo) {
      return this.__actionInit.getExpressMiddleware(domain, routeInfo);
    };

    return ActionInitializer;

  })();

  module.exports = ActionInitializer;

}).call(this);
