// Generated by CoffeeScript 1.6.2
(function() {
  var ActionConditioner, CriscoActionInit;

  CriscoActionInit = require("" + __dirname + "/../middleware.action/init");

  ActionConditioner = (function() {
    function ActionConditioner(database) {
      this.__db = database;
      this.__actionInit = new CriscoActionInit(this.__db);
      this.__actionInit.init();
    }

    /*
      Method: get
    
      Returns an array of express compliant middleware that
      initializes Crisco primitives. For now Actions
      aren't separated into domains like resources...
    */


    ActionConditioner.prototype.get = function() {
      return this.__actionInit.getExpressMiddleware();
    };

    return ActionConditioner;

  })();

  module.exports = ActionConditioner;

}).call(this);
