// Generated by CoffeeScript 1.4.0
(function() {
  var CriscoModel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CriscoModel = (function() {

    function CriscoModel(domain, database) {
      this.populate = __bind(this.populate, this);
      this.__domain = domain;
      this.__database = database;
    }

    CriscoModel.prototype.populate = function(clbk) {};

    CriscoModel.prototype.targets = function() {};

    return CriscoModel;

  })();

  module.exports = CriscoModel;

}).call(this);
