// Generated by CoffeeScript 1.4.0
(function() {
  var CriscoModels,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CriscoModels = (function() {

    function CriscoModels() {
      this.populate = __bind(this.populate, this);

    }

    CriscoModels.prototype.populate = function(clbk) {};

    return CriscoModels;

  })();

  module.exports = CriscoModels;

}).call(this);
