// Generated by CoffeeScript 1.6.2
(function() {
  var CriscoModel, CriscoModelFactory;

  CriscoModel = require("" + __dirname + "/criscomodel");

  /*
    Class: CriscoModelFactory
  
    Responsible for configuring CriscoModel
    instances for  each domain given an application
    config.
  */


  CriscoModelFactory = (function() {
    /*
      Method: constructor
    
      @param appConfig {Object} - A Crisco Application Configuration
      @param domains {Object} -
        {
          ADomainName: ["array of domain configs"]
        }
    */
    function CriscoModelFactory(appConfig, database) {
      this.__appConfig = appConfig;
      this.__database = database;
      this.__criscoModels = {};
    }

    CriscoModelFactory.prototype.get = function(domain) {
      var r,
        _this = this;

      console.log("Getting CriscoModel for domain " + domain);
      r = {
        init: function(req) {
          var routeInfo;

          routeInfo = {
            route: _.extend(req.route, {
              url: req.url
            }),
            method: req.method,
            query: req.query,
            body: req.body
          };
          return new CriscoModel(domain, _this.__database, routeInfo);
        }
      };
      return r;
    };

    return CriscoModelFactory;

  })();

  module.exports = CriscoModelFactory;

}).call(this);
