// Generated by CoffeeScript 1.4.0

/*
  Class: CriscoModelFactory

  Responsible for configuring CriscoModel
  instances for  each domain given an application
  config.
*/


(function() {
  var CriscoModelFactory;

  CriscoModelFactory = (function() {
    /*
        Method: constructor
    
        @param appConfig {Object} - A Crisco Application Configuration
        @param domains {Object} -
          {
            ADomainName: ["array of domain configs"]
          }
    */

    function CriscoModelFactory(appConfig, domains, database) {
      this.__appConfig = appConfig;
      this.__domains = domains;
      this.__database = database;
      this.__criscoModels = {};
    }

    CriscoModelFactory.prototype.get = function(domain) {
      return console.log("Getting domain " + domain);
    };

    return CriscoModelFactory;

  })();

  module.exports = CriscoModelFactory;

}).call(this);
