// Generated by CoffeeScript 1.6.2
(function() {
  var ApplicationInitializer, AuthenticationMiddleware, BaseAction, BaseResource, Crisco, Getter, PermissionMiddleware;

  BaseAction = require("" + __dirname + "/action/base");

  BaseResource = require("" + __dirname + "/resource/base");

  Getter = require("" + __dirname + "/../helpers/getter");

  ApplicationInitializer = require("" + __dirname + "/initializers/app");

  /*
    Default Middleware
  */


  PermissionMiddleware = require("" + __dirname + "/middleware/default/permission");

  AuthenticationMiddleware = require("" + __dirname + "/middleware/default/authentication");

  /*
    Class: Crisco
  
    Application class that exports application level functions.
  
    Also exposes enriched BaseAction and BaseResource classes.
  */


  Crisco = (function() {
    /*
      Method: constructor
    */
    function Crisco(config) {
      this.__config = config;
      this.__customMiddleware = {};
      global.Crisco = this;
    }

    /*
      Method: registerMiddleware
    
      Allows clients to registers middleware for use in action and route
      definitions.  For now each middleware module is registered for both
      actions and resources.
    */


    Crisco.prototype.registerMiddleware = function(name, middleware) {
      this.__customMiddleware[name] = middleware;
      BaseAction.register(name, middleware);
      return BaseResource.register(name, middleware);
    };

    Crisco.prototype.getMiddleware = function(name) {
      return this.__customMiddleware[name];
    };

    Crisco.prototype.start = function(clbk) {
      var actionsGetter, app, config, dbSettingsGetter, pluginGetter, resourceGetter, schemasGetter,
        _this = this;

      config = this.__config;
      schemasGetter = new Getter(config.schemaPath);
      resourceGetter = new Getter(config.resourcePath);
      pluginGetter = new Getter(config.pluginPath);
      dbSettingsGetter = new Getter(config.dbSettingsPath);
      actionsGetter = new Getter(config.actionsPath);
      /*
        Register Default Middleware
          -Authentication
          -Permissions
      */

      this.registerMiddleware("verifyPermissions", PermissionMiddleware);
      this.registerMiddleware("authenticate", AuthenticationMiddleware);
      app = new ApplicationInitializer(actionsGetter, resourceGetter, schemasGetter, pluginGetter, dbSettingsGetter);
      return app.init(function(err, express) {
        return clbk(err, express);
      });
    };

    /*
      Getters
    */


    Crisco.prototype.__defineGetter__('BaseAction', function() {
      return BaseAction.clone();
    });

    Crisco.prototype.__defineGetter__('BaseResource', function() {
      return BaseResource.clone();
    });

    Crisco.prototype.__defineGetter__('appConfig', function() {
      return this.__config;
    });

    return Crisco;

  })();

  module.exports = Crisco;

}).call(this);
