// Generated by CoffeeScript 1.4.0
(function() {
  var ApplicationInitializer, BaseAction, BaseResource, Crisco, Getter;

  BaseAction = require("" + __dirname + "/action/base");

  BaseResource = require("" + __dirname + "/resource/base");

  Getter = require("" + __dirname + "/../helpers/getter");

  ApplicationInitializer = require("" + __dirname + "/initializers/app");

  /*
    Class: Crisco
  
    Application class that exports application level functions.
  
    Also exposes enriched BaseAction and BaseResource classes.
  */


  Crisco = (function() {
    /*
        Method: constructor
    */

    function Crisco(config) {
      this._config = config;
      this._customMiddleware = {};
      global.Crisco = this;
    }

    /*
        Method: registerMiddleware
    
        Allows clients to registers middleware for use in action and route
        definitions.  For now each middleware module is registered for both
        actions and resources.
    */


    Crisco.prototype.registerMiddleware = function(name, middleware) {
      this._customMiddleware[name] = middleware;
      BaseAction.register(name, middleware);
      return BaseResource.register(name, middleware);
    };

    Crisco.prototype.start = function(clbk) {
      var actionsGetter, app, config, dbSettingsGetter, pluginGetter, resourceGetter, schemasGetter,
        _this = this;
      config = this._config;
      schemasGetter = new Getter(config.schemaPath);
      resourceGetter = new Getter(config.resourcePath);
      pluginGetter = new Getter(config.pluginPath);
      dbSettingsGetter = new Getter(config.dbSettingsPath);
      actionsGetter = new Getter(config.actionsPath);
      app = new ApplicationInitializer(schemasGetter, resourceGetter, pluginGetter, dbSettingsGetter, actionsGetter);
      return app.init(function(err) {
        return console.log("App Initialized");
      });
    };

    /*
        BaseAction and BaseResource Getters
    */


    Crisco.prototype.__defineGetter__('BaseAction', function() {
      return BaseAction;
    });

    Crisco.prototype.__defineGetter__('BaseResource', function() {
      return BaseResource;
    });

    return Crisco;

  })();

  module.exports = Crisco;

}).call(this);
