// Generated by CoffeeScript 1.6.2
/*
  This stub initializes the application state...also allows state serialization
  and deserialization so that clients can easily use and inspect the state of
  this action class instance.
*/


(function() {
  var BaseAction;

  BaseAction = (function() {
    function BaseAction() {}

    BaseAction.register = function(name, middleware) {
      this._m = this._m || {};
      return this._m[name] = middleware;
    };

    BaseAction.clone = function() {
      var f;

      f = function() {};
      f._routes = [];
      f.__vars = {};
      f._d = 'default';
      /*
        Before and After hooks
      */

      f.before = function(beforeHooks) {
        return this.__vars.bh = beforeHooks;
      };
      f.after = function(afterHooks) {
        return this.__vars.ah = afterHooks;
      };
      f.app = function() {};
      f.domain = function(d) {
        return this._d = d;
      };
      f.app.action = function(route, actionHandler) {
        return console.log("Action !", route);
      };
      f._reset = function() {
        return this.__vars.t = null;
      };
      f.serialize = function() {
        var o;

        o = {
          domain: f.__vars.d || "default",
          beforeHooks: f.__vars.bh,
          afterHooks: f.__vars.ah,
          routes: f._routes,
          m: BaseAction._m
        };
        return o;
      };
      f.deserialize = function(conf) {
        this.__vars.d = conf.domain || this.__vars.d;
        this.__vars.bh = conf.beforeHooks || this.__vars.bh;
        this.__vars.ah = conf.afterHooks || this.__vars.ah;
        return this._routes = conf.routes || this._routes;
      };
      return f;
    };

    return BaseAction;

  })();

  module.exports = BaseAction;

}).call(this);
