// Generated by CoffeeScript 1.4.0

/*
  This stub initializes the application state...also allows state serialization
  and deserialization so that clients can easily use and inspect the state of
  this action class instance.
*/


(function() {
  var BaseAction;

  BaseAction = (function() {

    function BaseAction() {}

    BaseAction.register = function(name, middleware) {
      this._m = this._m || {};
      return this._m[name] = middleware;
    };

    BaseAction.clone = function() {
      var f, mDef, mName, _ref;
      f = function() {};
      f._routes = [];
      f._d = 'default';
      if (this._m != null) {
        _ref = this._m;
        for (mName in _ref) {
          mDef = _ref[mName];
          f[mName] = mDef;
        }
      }
      f.app = function() {};
      f.domain = function(d) {
        return this._d = d;
      };
      f.app.action = function(route, actionHandler) {
        return console.log("Action !", route);
      };
      f._reset = function() {
        return this._t = null;
      };
      f.serialize = function() {
        return f._routes;
      };
      return f;
    };

    return BaseAction;

  })();

  module.exports = BaseAction;

}).call(this);
