// Generated by CoffeeScript 1.6.2
(function() {
  var CriscoActionRoute;

  CriscoActionRoute = (function() {
    function CriscoActionRoute(config) {
      this._c = config;
    }

    CriscoActionRoute.prototype.build = function() {
      return console.log("Building action route");
    };

    CriscoActionRoute.prototype.enrich = function(express) {
      return console.log("Enriching express instance with this route");
    };

    return CriscoActionRoute;

  })();

  module.exports = CriscoActionRoute;

}).call(this);
