// Generated by CoffeeScript 1.4.0

/*
  Crisco app handlers

  // Crisco.coffee
*/


(function() {
  var CriscoRouter;

  CriscoRouter = (function() {

    function CriscoRouter(middleware) {
      this._m = middleware;
    }

    CriscoRouter.prototype.get = function() {
      var _this = this;
      return this._m.forEach(function(m) {});
    };

    CriscoRouter.prototype.post = function() {};

    CriscoRouter.prototype.put = function() {};

    CriscoRouter.prototype.del = function() {};

    return CriscoRouter;

  })();

  module.exports = CriscoRouter;

}).call(this);
