// Generated by CoffeeScript 1.4.0
(function() {
  var DEL,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DEL = (function() {

    function DEL() {
      this.handler = __bind(this.handler, this);
      console.log("Initializing default DEL");
    }

    DEL.prototype.handler = function() {};

    DEL.prototype.__defineGetter__('route', function() {
      return "/api/resource/del";
    });

    return DEL;

  })();

  module.exports = DEL;

}).call(this);
