// Generated by CoffeeScript 1.4.0
(function() {
  var GET,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  GET = (function() {

    function GET() {
      this.handler = __bind(this.handler, this);
      console.log("Initializing default GET");
    }

    GET.prototype.handler = function() {};

    GET.prototype.__defineGetter__('route', function() {
      return "/api/resource/get";
    });

    return GET;

  })();

  module.exports = GET;

}).call(this);
