// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(CriscoModels, Aux, next) {
    var res;
    console.log("Running Authentication Middleware");
    if (Aux.me == null) {
      res = Aux.res;
      return res.json(401, {
        message: "User is not authenticated. Please create a session."
      });
    } else {
      return next();
    }
  };

}).call(this);
