// Generated by CoffeeScript 1.6.2
(function() {
  var _;

  _ = require("underscore");

  module.exports = function(CriscoModels, Aux, next) {
    var deny, resourceId, root,
      _this = this;

    console.log("Running Feature Flag Middleware");
    deny = function() {
      return Aux.response.status(401).message("Not Authorized").send();
    };
    if ((root = CriscoModels.getRoot()) == null) {
      console.log("Cannot find root node. Denying...");
      return deny();
    } else {
      console.log("Checking root configuration", root.configuration);
      if (root.configuration.featureFlags == null) {
        console.log("Route " + Aux.req.originalUrl + " does not have featureFlags. Skipping...");
        return next();
      } else {
        resourceId = CriscoModels.getParam(root.alternateName);
        return Aux.me.getFeatureFlags(root.name, {
          _id: resourceId
        }, function(featureFlags) {
          var confFlags;

          console.log("Teacher feature flags", featureFlags);
          confFlags = root.configuration.featureFlags;
          if (_.intersection(confFlags, featureFlags).length === confFlags.length) {
            return next();
          } else {
            return deny();
          }
        });
      }
    }
  };

}).call(this);
