// Generated by CoffeeScript 1.6.2
(function() {
  var DEL,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DEL = (function() {
    function DEL(crisco, r) {
      this.handler = __bind(this.handler, this);      this.__c = crisco;
      this.__r = r;
    }

    DEL.prototype.handler = function(req, res, next) {};

    DEL.prototype.__defineGetter__('route', function() {
      return this.__r.route;
    });

    return DEL;

  })();

  module.exports = DEL;

}).call(this);
