// Generated by CoffeeScript 1.6.2
(function() {
  var DEL,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DEL = (function() {
    function DEL(crisco, r) {
      this.handler = __bind(this.handler, this);      console.log("Initializing default DEL");
    }

    DEL.prototype.handler = function() {};

    DEL.prototype.__defineGetter__('route', function() {
      return "/api/resource/del";
    });

    return DEL;

  })();

  module.exports = DEL;

}).call(this);
