// Generated by CoffeeScript 1.6.2
(function() {
  var POST,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  POST = (function() {
    function POST(crisco, r) {
      this.handler = __bind(this.handler, this);      console.log("Initializing default POST");
    }

    POST.prototype.handler = function() {};

    POST.prototype.__defineGetter__('route', function() {
      return "/api/resource/post";
    });

    return POST;

  })();

  module.exports = POST;

}).call(this);
