// Generated by CoffeeScript 1.6.2
(function() {
  var PUT,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PUT = (function() {
    function PUT(crisco, r) {
      this.handler = __bind(this.handler, this);      this.__c = crisco;
      this.__r = r;
    }

    PUT.prototype.handler = function(req, res, next) {};

    PUT.prototype.__defineGetter__('route', function() {
      return this.__r.route;
    });

    return PUT;

  })();

  module.exports = PUT;

}).call(this);
